# Generated by Django 5.0.1 on 2024-02-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='categories',
            field=models.ManyToManyField(to='management.category'),
        ),
    ]
