# Generated by Django 5.0.6 on 2024-09-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
