# Generated by Django 5.0.1 on 2024-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_expense_date_alter_expense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
